title: "QR-VC: Leveraging Quantization Residuals for Linear Disentanglement in Zero-Shot Voice Conversion"
description: "Youngjun Sim, Jinsung Yoon, Wooyeol Jeong, Young-Joo Suh"
show_downloads: true
google_analytics: # Optional: Add your Google Analytics ID here
theme: "jekyll-theme-cayman"
