title: "SKQVC: One-Shot Voice Conversion by K-Means Quantization with Self-Supervised Speech Representations"
description: "asdfsafsfsaf"
show_downloads: true
google_analytics: # Optional: Add your Google Analytics ID here
theme: "jekyll-theme-cayman"
